---
# tasks file for roles/join-workers

   - name: Join the Worker nodes to the cluster.
     become: yes
     shell: "{{ hostvars['master']['kubernetes_join_command'] }}"
     register: joined_or_not