- name: Install Kubernetes with CRI-O
  hosts: all
  become: yes

  tasks:
    - name: Disable swap
      sysctl:
        name: vm.swappiness
        value: 0
        state: present

    - name: Unmount swap
      mount:
        name: swap
        fstype: swap
        state: absent

    - name: Remove swap entry from /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^/dev/mapper/ubuntu--vg-swap_1'
        state: absent

    - name: Install CRI-O dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - software-properties-common
        - apt-transport-https
        - ca-certificates
        - curl

    - name: Add CRI-O repository key
      apt_key:
        url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Ubuntu_$(lsb_release -rs)/Release.key

    - name: Add CRI-O repository
      apt_repository:
        repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Ubuntu_$(lsb_release -rs)/ /
        state: present
        filename: cri-o

    - name: Install CRI-O
      apt:
        name: cri-o
        state: present

    - name: Enable and start CRI-O service
      systemd:
        name: crio
        enabled: yes
        state: started

    - name: Set up Kubernetes repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes
        update_cache: yes
        keyserver: keyserver.ubuntu.com

    - name: Install Kubernetes packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - kubelet
        - kubeadm
        - kubectl

    - name: Enable kubelet service
      systemd:
        name: kubelet
        enabled: yes
        state: started

