- name: Install Kubernetes with CRI-O
  hosts: all
  become: yes

  vars:
    # Change the Kubernetes version to match your needs
    OS: xUbuntu_20.04

  tasks:
    - name: Disable swap
      sysctl:
        name: vm.swappiness
        value: 0
        state: present

    - name: Unmount swap
      mount:
        name: swap
        fstype: swap
        state: absent

    - name: Remove swap entry from /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^/dev/mapper/ubuntu--vg-swap_1'
        state: absent

    - name: Install CRI-O dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - software-properties-common
        - apt-transport-https
        - ca-certificates
        - curl

    - name: Get Cri-o apt-key
      apt_key: 
        url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ OS }}/Release.key
        state: present

    - name: Get Cri-o apt-key
      apt_key: 
        url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ VERSION }}/{{ OS}}/Release.key
        state: present


    - name: Add Cri-o stable repo
      apt_repository:
        repo: "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ OS }}/ /"
        state: present
        filename: cri-o-stable

    - name: Add Cri-o stable repo
      apt_repository:
        repo: "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ VERSION }}/{{ OS }}/ /"
        state: present
        filename: cri-o-{{ VERSION }}

    - name: update apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Set up Kubernetes repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes
        update_cache: yes
        keyserver: keyserver.ubuntu.com

    - name: Install Kubernetes packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - kubelet
        - kubeadm
        - kubectl

    - name: Enable kubelet service
      systemd:
        name: kubelet
        enabled: yes
        state: started

