---
- name: Install Kubernetes on Ubuntu
  hosts: all
  become: true

  tasks:
    # Install prerequisites
    - name: Install apt-transport-https, curl and gnupg
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - curl
        - gnupg

    # Add Kubernetes signing key
    - name: Add Kubernetes signing key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    # Add Kubernetes repository
    - name: Add Kubernetes repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    # Install Kubernetes components
    - name: Install Kubernetes components
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - kubelet
        - kubeadm
        - kubectl

    # Initialize Kubernetes cluster on the first node
    - name: Initialize Kubernetes cluster on first node
      command: kubeadm init --pod-network-cidr=192.168.0.0/16
      when: inventory_hostname == groups['all'][0]
