---
- name: Install Kubernetes on Ubuntu
  hosts: all
  become: true

  vars:
    kubernetes_version: "1.25.1-00"
    
  tasks:
    # Install prerequisites
    - name: Install apt-transport-https, curl and gnupg
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - curl
        - gnupg

    - name: Set vm.swappiness to 0
      sysctl:
        name: vm.swappiness
        value: 0
        state: present

    - name: Comment out swap partition in /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^/dev/mapper/swap'
        line: '#/dev/mapper/swap none swap sw 0 0'

    # Add Kubernetes signing key
    - name: Add Kubernetes signing key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    # Add Kubernetes repository
    - name: Add Kubernetes repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    # Install Kubernetes components
    - name: Install Kubernetes components
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - kubelet={{kubernetes_version}}
        - kubeadm={{kubernetes_version}}
        - kubectl={{kubernetes_version}}

    # Initialize Kubernetes cluster on the first node
    - name: Initialize Kubernetes cluster on first node
      command: kubeadm init --pod-network-cidr=192.168.0.0/16
      when: inventory_hostname == groups['all'][0]
