---
- name: Install Kubernetes cluster
  hosts: all
  become: true

  tasks:
  - name: Update apt cache
    apt: update_cache=yes

  - name: Install required packages
    apt: name={{ item }} state=present
    with_items:
      - docker.io
      - apt-transport-https
      - curl

  - name: Add Kubernetes apt key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Add Kubernetes apt repository
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present

  - name: Install Kubernetes packages
    apt: name={{ item }} state=present
    with_items:
      - kubelet
      - kubeadm
      - kubectl

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Initialize Kubernetes cluster
    command: kubeadm init --pod-network-cidr=10.244.0.0/16
    register: join_command
    when: inventory_hostname == groups['kubernetes-master'][0]

  - name: Copy Kubernetes configuration
    command: mkdir -p $HOME/.kube && cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    args:
      creates: $HOME/.kube/config
    when: inventory_hostname == groups['kubernetes-master'][0]

  - name: Install flannel network
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    when: inventory_hostname == groups['kubernetes-master'][0]

  - name: Join Kubernetes cluster
    command: "{{ join_command.stdout_lines[0] }}"
    when: inventory_hostname in groups['kubernetes-node']
