---
# tasks file for roles/master-k8

    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=unix:///run/containerd/containerd.sock
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
      become: yes

    - name: create .labuser directory
      become: yes
      become_user: labuser
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copies admin.conf to user's kube config
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/labuser/.kube/config
        remote_src: yes
        owner: labuser

    - name: install Pod network
      become: yes
      become_user: labuser
      shell: kubectl apply -f https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml
      args:
        chdir: $HOME
        
    - name: Get the token for joining the worker nodes
      become: yes
      become_user: labuser
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"

