---
# tasks file for users

    - name: allow 'labuser' to use sudo without needing a password
      lineinfile:
        dest: /etc/sudoers
        line: 'labuser ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the labuser user
      authorized_key: user=labuser key="{{item}}"
      with_file:
        - ~/.ssh/id_ecdsa.pub