---
# tasks file for users

    - name: allow 'user" to use sudo without needing a password
      lineinfile:
        dest: /etc/sudoers
        line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      become: true

    - name: set up authorized keys for the "{{ ansible_user }}" user
      authorized_key: user="{{ ansible_user }}" key={{lookup('ansible.builtin.file', 'files/id_ecdsa.pub') }}
      become: true      
